/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    BellOutlined: typeof import('@ant-design/icons-vue')['BellOutlined']
    ChMachineGroup: typeof import('./src/components/iot-viewer/custom-comps/ch-machine-group/index.vue')['default']
    ChwpGroup: typeof import('./src/components/iot-viewer/custom-comps/chwp-group.vue')['default']
    ColdStorageTower: typeof import('./src/components/iot-viewer/custom-comps/cold-storage-tower.vue')['default']
    ColdTowerGroup: typeof import('./src/components/iot-viewer/custom-comps/cold-tower-group.vue')['default']
    CompressGroup: typeof import('./src/components/iot-viewer/custom-comps/compress-group.vue')['default']
    copy: typeof import('./src/components/iot-viewer/custom-comps/sec-refrigerator-group copy.vue')['default']
    DownOutlined: typeof import('@ant-design/icons-vue')['DownOutlined']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MenuFoldOutlined: typeof import('@ant-design/icons-vue')['MenuFoldOutlined']
    MenuUnfoldOutlined: typeof import('@ant-design/icons-vue')['MenuUnfoldOutlined']
    RefrigeratorGroup: typeof import('./src/components/iot-viewer/custom-comps/refrigerator-group/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecRefrigeratorGroup: typeof import('./src/components/iot-viewer/custom-comps/sec-refrigerator-group.vue')['default']
    SimpleForm: typeof import('./src/components/simple-form/index.vue')['default']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    VerifyCode: typeof import('./src/components/verify-code/index.vue')['default']
  }
}
